### ISSUE TITLE
AttributeError: module 'stft' has no attribute 'spectrogram'

### ISSUE THREAD

**Issue by trov4** [nils-werner/stft#11]
### Problem 
 I'm not able to call the function `stft.spectrogram`, after following the tutorials [here](https://stft.readthedocs.io/en/latest/examples.html). Here is my console output: 

```
makeing spectrogram for file: data/055 - Angels In Amplifiers - I'm Alright.wav
/usr/lib/python3/dist-packages/scipy/io/wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
Traceback (most recent call last):
  File "/mnt/c/Users/tstan/Documents/Class spring 21/ML/Project/stft.py", line 1, in <module>
    import stft 
  File "/mnt/c/Users/tstan/Documents/Class spring 21/ML/Project/stft.py", line 18, in <module>
    specgram = stft.spectrogram(audio)
AttributeError: module 'stft' has no attribute 'spectrogram'
``` 

### About my system 
I've ran into this on both Windows and Linux (runnign wsl--yes it runs a python executeable on the linux side)   
I've tried fixing this with running both python 2.7 and 3.7.

Any help on how to fix this? 
Thanks,
-T

**Comment by nils-werner** [comment]
Hi, this sounds like a very common issue: your Python file `stft.py` is shadowing the module `stft`. Rename the file and it should work.

**Comment by trov4** [comment]
Yep that fixed it. thanks!
