### ISSUE TITLE
How to specify the sampling frequency?

### ISSUE THREAD

**Issue by yfiua** [nils-werner/stft#7]

**Comment by nils-werner** [comment]
You don't need to, depending on your sampling frequency the spectrogram bins are centered around  different frequencies, but the transform itself does not need to know the sampling frequency.

What do you want to achieve?

**Comment by yfiua** [comment]
E.g. I want to know the frequency distribution for each bin?

**Comment by nils-werner** [comment]
You can use [`numpy.fft.fftfreq`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html) for that.

**Comment by yfiua** [comment]
Ty
